config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'plays#index'
  devise_for :users
  resources :users
  resources :plays do
    resources :comments
    resources :favorites, only: %i[create destroy]
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :play
  validates :content, presence: true
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_play

  def create
    @comment = @play.comments.build(comment_params)
    @comment.user_id = current_user.id
    render :index if @comment.save
  end

  def destroy
    @comment = Comment.find(params[:id])
    render :index if @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :play_id, :user_id)
  end

  def set_play
    @play = Play.find(params[:play_id])
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [play, comment] ) do |form| %>
  <div>
    <%= form.text_field :content %>
  </div>
  <div class="actions"></div>
    <%= form.submit "コメント" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <p><%= link_to image_tag(comment.user.avatar.variant(combine_options:{resize:"55x55^",crop:"55x55+0+0",gravity: :center, border:'3',bordercolor:'black'})),user_path(comment.user) %> <%= comment.content %></p>
    <% if comment.user == current_user %>
      <p><%= link_to 'コメントを削除する', play_comment_path(comment.play_id, comment.id), method: :delete, remote: true %></p>
    <% end %>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index',{ comments: @comment.play.comments }) %>")
$("textarea").val('')