config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'plays#index'
  devise_for :users
  resources :users
  resources :plays do
    resources :comments
    resources :favorites, only: %i[create destroy]
  end
end

app/models/play.rb
# frozen_string_literal: true

class Play < ApplicationRecord
  validates :description, length: { maximum: 400 }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  belongs_to :category, optional: true
  has_one_attached :image

  scope :random, -> { order('RANDOM()') }
  scope :related_plays, ->(category, number) {
    where(category_id: category.id)
      .includes(image_attachment: [:blob])
      .random
      .limit(number)
  }

  def favorite_user(user_id)
    favorites.find_by(user_id: user_id)
  end
end

app/controllers/plays_controller.rb
# frozen_string_literal: true

class PlaysController < ApplicationController
  MAX_LIMITED_NUMBER_PLAY = 5

  before_action :find_play, only: %i[show update]
  before_action :set_category, only: %i[new edit]
  before_action :owner_user?, only: %i[edit destroy]

  def index
    @plays = Play.includes(image_attachment: [:blob]).page(params[:page]).per(12)
  end

  def show
    @user = @play.user
    @category = Category.find_by(id: @play.category_id)
    @related_plays = Play.related_plays(@category, MAX_LIMITED_NUMBER_PLAY).where.not(id: @play.id)
    @comment = Comment.new
    @comments = @play.comments
  end

  def new
    @play = current_user.plays.build
  end

  def create
    @play = current_user.plays.build(play_params)
    @play.category_id = params[:category_id]
    if @play.save
      flash[:success] = "映画を投稿しました！"
      redirect_to play_path(@play)
    else
      render new
    end
  end

  def edit
  end

  def update
    if @play.update(play_params)
      redirect_to play_path(@play)
    else
      render edit
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

    def play_params
      params.require(:play).permit(:title, :description, :director, :image, :url)
    end

    def find_play
      @play = Play.find(params[:id])
    end

    def set_category
      @categories = Category.all.map { |c| [c.name, c.id] }
    end

    def owner_user?
      @play = current_user.plays.find_by(id: params[:id])
      redirect_to root_path if @play.nil?
    end
end

app/helpers/plays_helper.rb
# frozen_string_literal: true

module PlaysHelper
end

app/views/plays/_favorite.html.erb
<% if user_signed_in? %>
  <% if ! play.favorite_user(current_user) %>
    <%= button_to play_favorites_path(play), remote: true, method: :post do %> 
      <%= image_tag("icon_red_heart.png") %>
    <% end %>  
  <% else %>
    <%= button_to play_favorite_path(play.favorite_user(current_user.id), play_id: play.id), remote: true, method: :delete do %>
      <%= image_tag("icon_black_heart.png") %> <span>いいね解除</span>
    <% end %>  
  <% end %>  
<% end %>  

app/views/plays/_form.html.erb
<div class="panel-body">
  <%= simple_form_for @play do |f| %>
    <div class="select_tag">
      <%= select_tag(:category_id, options_for_select(@categories)) %>
    </div>
    <%= f.input :title, label: "題名" %>
    <%= f.input :description, label: "詳細" %>
    <%= f.input :director, label: "監督" %>
    <%= f.input :url, label: "予告編URL（youtube）" %>
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= f.file_field :image,  label: "画像"  %>
  <% end %>
</div>

app/views/plays/create.js.erb
$("#like-of-<%= @play.id %>").html("<%= escape_javascript(render partial: 'plays/favorite', locals: { play: @play }) %>")

app/views/plays/destroy.js.erb
$("#like-of-<%= @play.id %>").html("<%= escape_javascript(render partial: 'plays/favorite', locals: { play: @play, favorite: @favorites }) %>")

app/views/plays/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Edit Movie</h2>
      </div>  
        <%= render "form"%>
    </div>
  </div>
</div>  

app/views/plays/index.html.erb
<div class="row">
<% @search_plays.each do |play| %>
  <div class="col-md-3 text-center">
    <% if play.image.attached? %>
      <%= link_to (play_path(play)) do %>
        <%= image_tag play.image.variant(combine_options:{resize:"220x290^",crop:"220x290+0+0",gravity: :center, border:'2',bordercolor:'black'}) , class: "play-index" %> 
      <% end %>  
    <% end %>
  </div>  
<% end %>
</div>
<%= paginate @plays %>

app/views/plays/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Add New Movie</h2>
      </div>
      <%= render "form"%>
    </div>
  </div>
</div>      

app/views/plays/show.html.erb
<% provide(:title, @play.title) %>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body text-center"><%= image_tag @play.image.variant(combine_options:{resize:"325x475^",crop:"325x475+0+0",gravity: :center, border:'5',bordercolor:'black'}) %>
        Posted by <%= link_to @user.name, user_path(@user) %>
      </div>
      <div class="panel-footer play-update">
        <button class="btn btn-default"><%= link_to "Video", @play.url %></button>
        <% if user_signed_in? %>
          <% if @play.user_id == current_user.id %>
            <button class="btn btn-success"><%= link_to "編集", edit_play_path(@play) %></button>
            <button class="btn btn-danger"><%= link_to "削除", play_path(@play), method: :delete, data: {confirm: "Are you sure ?" } %></button>  
          <% end %>
        <% end %>
      </div>
    </div>
      <span id="like-of-<%= @play.id %>">
        <%= render "favorite", play: @play %>
      </span>  
  </div>  
  <div class="col-md-8 play-show">
    <h1><%= @play.title %></h2>
    <h2><%= @play.director %></h2>
    <h5>カテゴリー：<%= @play.category.name %></h5>
    <p><%= @play.description %></p>
    <p class="row related_image">
      <P class="related-plays"><関連作品></P>
      <% @related_plays.each do |related_play| %>
        <%= link_to (play_path(related_play)) do %>
          <%= image_tag related_play.image.variant(combine_options:{resize:"140x190^",crop:"140x190+0+0",gravity: :center, border:'3',bordercolor:'black'}) %>
        <% end %>
      <% end %> 
    </p>  
    <p><コメント></p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments } %>
      <% if user_signed_in? %>
        <%= render partial: 'comments/form', locals: { comment: @comment, play: @play } %>
      <% else %>
        <%= button_to "ログインしてコメントしてみよう!", new_user_session_path , class: "btn btn-info" %>  
      <% end %>
    </div>
  </div>
</div>