config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'plays#index'
  devise_for :users
  resources :users
  resources :plays do
    resources :comments
    resources :favorites, only: %i[create destroy]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :avatar, presence: false
  has_many :plays, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :fav_movies, through: :favorites, source: :play
  has_one_attached :avatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name avatar])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name avatar])
  end

  def after_sign_up_path_for(_resource)
    plays_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all.includes(avatar_attachment: [:blob])
  end

  def show
    @user = User.find(params[:id])
    @plays = @user.plays.all.includes(image_attachment: [:blob])
    @fav_movies = @user.fav_movies.includes(image_attachment: [:blob])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/index.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col-md-4">
      <%= link_to (user_path(user)) do %>
        <% if user.avatar.attached? %>
          <%= image_tag user.avatar.variant(combine_options:{resize:"280x280^",crop:"280x280+0+0",gravity: :center,border:'3',bordercolor:'black'}) %>
          <p class="color-white"><%= user.name %>のfavorites Movie</p>
        <% else %>
          <%= user.name %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-5">
    <%= image_tag @user.avatar.variant(combine_options:{resize:"350x400^",crop:"350x400+0+0",gravity: :center, border:'3',bordercolor:'black'}) %>
    <h4>ユーザー名: <%= @user.name %></h4>  
    <% if @user.fav_movies.any? %>
      <h4 class="related_image"><いいねしたMovie一覧><h4>
        <% @fav_movies.each do |movie| %>
          <%= link_to image_tag(movie.image.variant(combine_options:{resize:"100x150^",crop:"100x150+0+0",gravity: :center, border:'3',bordercolor:'black'})),play_path(movie) %>
        <% end %> 
    <% end %> 
    <% if @user.comments.any? %>    
      <h4 class="related_image"><コメント一覧></h4>
       <% @user.comments.each do |comment| %>
       <P>
        <%= comment.content %> 
        ＠<%= link_to comment.play.title, play_path(comment.play) %>
       </P>  
      <% end %>  
    <% end %>  
  </div>
  <div class="col-md-4">
    <h4><投稿したMOVIE一覧></h4>
    <% @plays.each do |play| %>  
      <div class="panel panel-default">
        <div class="panel-heading"><h5><%= play.title %></h5></div>
          <div class="panel-body">
              <p class="text-center">
                <% if play.image.attached? %>
                  <%= link_to image_tag(play.image.variant(combine_options:{resize:"280x320^",crop:"280x320+0+0",gravity: :center})),play_path(play) %>
                <% end %>
              </p>
          </div>
        </div>      
    <% end %>
      </div>     
  </div>
</div>