config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'plays#index'
  devise_for :users
  resources :users
  resources :plays do
    resources :comments
    resources :favorites, only: %i[create destroy]
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :plays
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :play
  validates :content, presence: true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :play
end

app/models/play.rb
# frozen_string_literal: true

class Play < ApplicationRecord
  validates :description, length: { maximum: 400 }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  belongs_to :category, optional: true
  has_one_attached :image

  scope :random, -> { order('RANDOM()') }
  scope :related_plays, ->(category, number) {
    where(category_id: category.id)
      .includes(image_attachment: [:blob])
      .random
      .limit(number)
  }

  def favorite_user(user_id)
    favorites.find_by(user_id: user_id)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :avatar, presence: false
  has_many :plays, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :fav_movies, through: :favorites, source: :play
  has_one_attached :avatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: %i[create edit update destroy]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

def set_search
  @search = Play.includes(image_attachment: [:blob]).ransack(params[:q]) 
  @search_plays = @search.result.page(params[:page]).per(12)
end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name avatar])
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_play

  def create
    @comment = @play.comments.build(comment_params)
    @comment.user_id = current_user.id
    render :index if @comment.save
  end

  def destroy
    @comment = Comment.find(params[:id])
    render :index if @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :play_id, :user_id)
  end

  def set_play
    @play = Play.find(params[:play_id])
  end
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

class FavoritesController < ApplicationController
  before_action :set_play

  def create
    @favorite = Favorite.create(user_id: current_user.id, play_id: params[:play_id])
    render 'plays/create.js.erb'
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, play_id: params[:play_id])
    favorite.destroy
    render 'plays/destroy.js.erb'
  end

  def set_play
    @play = Play.find(params[:play_id])
  end
end

app/controllers/plays_controller.rb
# frozen_string_literal: true

class PlaysController < ApplicationController
  MAX_LIMITED_NUMBER_PLAY = 5

  before_action :find_play, only: %i[show update]
  before_action :set_category, only: %i[new edit]
  before_action :owner_user?, only: %i[edit destroy]

  def index
    @plays = Play.includes(image_attachment: [:blob]).page(params[:page]).per(12)
  end

  def show
    @user = @play.user
    @category = Category.find_by(id: @play.category_id)
    @related_plays = Play.related_plays(@category, MAX_LIMITED_NUMBER_PLAY).where.not(id: @play.id)
    @comment = Comment.new
    @comments = @play.comments
  end

  def new
    @play = current_user.plays.build
  end

  def create
    @play = current_user.plays.build(play_params)
    @play.category_id = params[:category_id]
    if @play.save
      flash[:success] = "映画を投稿しました！"
      redirect_to play_path(@play)
    else
      render new
    end
  end

  def edit
  end

  def update
    if @play.update(play_params)
      redirect_to play_path(@play)
    else
      render edit
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

    def play_params
      params.require(:play).permit(:title, :description, :director, :image, :url)
    end

    def find_play
      @play = Play.find(params[:id])
    end

    def set_category
      @categories = Category.all.map { |c| [c.name, c.id] }
    end

    def owner_user?
      @play = current_user.plays.find_by(id: params[:id])
      redirect_to root_path if @play.nil?
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all.includes(avatar_attachment: [:blob])
  end

  def show
    @user = User.find(params[:id])
    @plays = @user.plays.all.includes(image_attachment: [:blob])
    @fav_movies = @user.fav_movies.includes(image_attachment: [:blob])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Favorite Movie'
    if page_title. blank?
      base_title
    else
      page_title
    end
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/favorites_helper.rb
# frozen_string_literal: true

module FavoritesHelper
end

app/helpers/plays_helper.rb
# frozen_string_literal: true

module PlaysHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light" style="background-color:black">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" id="logo">Favarite Movie</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-text navbar-center">
        <%= search_form_for @search, url: plays_path do |f| %>
      <dt>
        <%= f.text_field :title_cont ,placeholder: '映画タイトルで検索...' %>
        <%= f.submit ("serch") , class: 'btn btn-primary'%>
      </dt>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-text navbar-right">
          <ul class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><button class="btn btn-dark">
            Menu<b class="caret"></b></button>
          </a>
          <ul class="dropdown-menu">
            <li><%= image_tag current_user.avatar.variant(combine_options:{resize:"160x160^",crop:"160x160+0+0",gravity: :center,border:'3',bordercolor:'black'}) %></li>
            <li class="divider"></li>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "All Users", users_path %></li>
            <li><%= link_to "Add New Movie", new_play_path%></li>
            <li class="divider"></li>
            <li>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
              <%= link_to "User settings", edit_user_registration_path(@user) %>
            </li>
          </ul>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-text navbar-right">
          <button class="btn btn-dark"><%= link_to "All User", users_path %></button>
          <button class="btn btn-info"><%= link_to 'Login', new_user_session_path %></button>
        </ul>
      <% end %>
    </div>
  </div>
</nav>
<p class="notice">
<%= notice %>
</p>
<p class="alert">
<%= alert %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
  </head>
  <body style="background-color: rgb(238, 235, 235);">
    <%= render "layouts/header" %>
    <div class="container">
        <%= yield %>
    </div>   
  </body>
</html>